#!/bin/bash

airmon-ng check kill
service dnsmasq stop
service hostapd stop
ifconfig wlan0 up
ifconfig wlan0 10.0.0.1/24
iptables -t nat -F
iptables -F
iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
iptables -A FORWARD -i wlan0 -o eth0 -j ACCEPT
echo -e '1' > /proc/sys/net/ipv4/ip_forward
iptables -t nat -A PREROUTING -p tcp --dport 80 -j DNAT --to-destination 192.168.0.100:80
iptables -t nat -A PREROUTING -p tcp --dport 443 -j DNAT --to-destination 192.168.0.100:443
service dnsmasq restart
service dnsmasq status
echo 'Sleeping 3 seconds before starting hostapd due to bug'
sleep 3
service hostapd restart
service hostapd status
